### ISSUE TITLE
Using with component that is added dynamically

### ISSUE THREAD

**Issue by josefsabl** [Arachne/EntityLoader#7]
Hello, I have a question.

Is it possible to use the entity loader with components that are not created by magic createComponent* method but are rather added by addComponent method? I am adding components dynamically.

I am referring to: "Add return types to all your createComponent methods." from installation documentation.

Thank you in advance.

**Comment by josefsabl** [comment]
Okay, I see that indeed it is not possible. I hacked it by adding dummy method createComponent* that does nothing but finder can use it to detect the type of the component. It would be cool if there was another way to hint the type of component to entity loader (Annotation for the containing class?).

**Comment by enumag** [comment]
What is the use case? As in why is the component not added using createComponent*?

**Comment by josefsabl** [comment]
We have a generalised and reusable search component (imagine grid on steroids) that consists of other components: result, filter (or several filters?), paginator, multiaction component, pagesize component, export results component etc... most are optional, some can have multiple instances etc... And this stuff is configured like this is neon.

```
services:
    -
        class: App\AdminModule\UsersModule\IndexModule\SearchFactory
        setup:
            - addComponentFactory(@app.admin.users.index.filterFactory, 'filter')
            - addComponentFactory(@app.admin.users.index.resultFactory, 'result')
            - addComponentFactory(@app.admin.users.index.paginatorFactory, 'paginator')
            - addComponentFactory(@app.admin.users.index.export, 'export')
```
